config/routes.rb
Mixtapefall::Application.routes.draw do
  resources :genres

  resources :artists

  resources :mixtapes

  resources :albums

  resources :songs

  root :to => 'songs#index'

end

app/models/mixtape.rb
class Mixtape < ActiveRecord::Base
  attr_accessible :mixtape_name

  has_many :mixtape_songs
  has_many :songs, :through => :mixtape_songs
end

app/controllers/mixtapes_controller.rb
class MixtapesController < ApplicationController
  # GET /mixtapes
  # GET /mixtapes.json
  def index
    @mixtapes = Mixtape.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mixtapes }
    end
  end

  # GET /mixtapes/1
  # GET /mixtapes/1.json
  def show
    @mixtape = Mixtape.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mixtape }
    end
  end

  # GET /mixtapes/new
  # GET /mixtapes/new.json
  def new
    @mixtape = Mixtape.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mixtape }
    end
  end

  # GET /mixtapes/1/edit
  def edit
    @mixtape = Mixtape.find(params[:id])
  end

  # POST /mixtapes
  # POST /mixtapes.json
  def create
    @mixtape = Mixtape.new(params[:mixtape])

    respond_to do |format|
      if @mixtape.save
        format.html { redirect_to @mixtape, notice: 'Mixtape was successfully created.' }
        format.json { render json: @mixtape, status: :created, location: @mixtape }
      else
        format.html { render action: "new" }
        format.json { render json: @mixtape.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mixtapes/1
  # PUT /mixtapes/1.json
  def update
    @mixtape = Mixtape.find(params[:id])

    respond_to do |format|
      if @mixtape.update_attributes(params[:mixtape])
        format.html { redirect_to @mixtape, notice: 'Mixtape was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mixtape.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mixtapes/1
  # DELETE /mixtapes/1.json
  def destroy
    @mixtape = Mixtape.find(params[:id])
    @mixtape.destroy

    respond_to do |format|
      format.html { redirect_to mixtapes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mixtapes_helper.rb
module MixtapesHelper
end

app/views/mixtapes/_form.html.erb
<%= form_for(@mixtape) do |f| %>
  <% if @mixtape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mixtape.errors.count, "error") %> prohibited this mixtape from being saved:</h2>

      <ul>
      <% @mixtape.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mixtape_name %><br />
    <%= f.text_field :mixtape_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mixtapes/edit.html.erb
<h1>Editing mixtape</h1>

<%= render 'form' %>

<%= link_to 'Show', @mixtape %> |
<%= link_to 'Back', mixtapes_path %>

app/views/mixtapes/index.html.erb
<h1>Listing mixtapes</h1>

<table>
  <tr>
    <th>Mixtape name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mixtapes.each do |mixtape| %>
  <tr>
    <td><%= mixtape.mixtape_name %></td>
    <td><%= link_to 'Show', mixtape %></td>
    <td><%= link_to 'Edit', edit_mixtape_path(mixtape) %></td>
    <td><%= link_to 'Destroy', mixtape, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mixtape', new_mixtape_path %>

app/views/mixtapes/new.html.erb
<h1>New mixtape</h1>

<%= render 'form' %>

<%= link_to 'Back', mixtapes_path %>

app/views/mixtapes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mixtape name:</b>
  <%= @mixtape.mixtape_name %>
</p>


<%= link_to 'Edit', edit_mixtape_path(@mixtape) %> |
<%= link_to 'Back', mixtapes_path %>